### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/P-ADesign#10]
> [Open in MURAL](https://app.mural.co/t/paladinarcher0959/m/paladinarcher0959/1598301853331?wid=0-1598388560403) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> Sprint 1 Storyboard - PALADIN & ARCHER
  
A non-manager will be able to track where they're at, what their current capabilities are, and use those as a baseline on what to learn next. 

- [ ] Interface for creating, removing, & editing capabilities

- [ ] Experience and coins are awarded for adding new capabilities 1-5 coins and 1 xp on any new capability

- [ ] NFR - Base this off the TSQ skills functionality 

- [ ] Self rating capability based off TSQ

- [ ] Ability to describe a capability
