### ISSUE TITLE
OKRs

### ISSUE THREAD

**Issue by CraigBuckmaster** [paladinarcher/P-ADesign#22]
> [Open in MURAL](https://app.mural.co/t/paladinarcher0959/m/paladinarcher0959/1598301853331?wid=0-1598388710339) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> Sprint 1 Storyboard - PALADIN & ARCHER

Tracking goals ensure you actually complete them! 
Tracking objectives and key results for goals enables non-managers to grow and achieve more than if they didn't. 

- [ ] Allow selection/creation of OKR board

- [ ] Create trello integration

- [ ] Write instructions for how to OKR w/ Trello

![image.png](https://images.zenhubusercontent.com/5ce6faa33b227d4dbc2e18d0/72851360-00c8-4d9e-a4ae-e02bb9dd5725)
